enum ActionType {
  GET_SUBSCRIPTIONS = 'GET_SUBSCRIPTIONS',
  GET_LATEST_EPISODES = 'GET_LATEST_EPISODES',
  SEND_PLAYBACK_INFO = 'SEND_PLAYBACK_INFO',
  GET_PLAYBACK_INFO = 'GET_PLAYBACK_INFO',
}

export default ActionType;
