enum ActionTypes {
  GET_SUBSCRIPTIONS = 'GET_SUBSCRIPTIONS',
  GET_LATEST_EPISODES = 'GET_LATEST_EPISODES',
  SET_PLAYBACK_INFO = 'SET_PLAYBACK_INFO',
  GET_PLAYBACK_INFO = 'GET_PLAYBACK_INFO',
  SET_PROGRESS = 'SET_PROGRESS',
  GET_PROGRESS = 'GET_PROGRESS',
}

export default ActionTypes;
