enum ActionType {
  GET_SUBSCRIPTIONS = 'GET_SUBSCRIPTIONS',
  GET_LATEST_EPISODES = 'GET_LATEST_EPISODES',
  SEND_PLAYBACK_INFO = 'SEND_PLAYBACK_INFO',
  GET_PLAYBACK_INFO = 'GET_PLAYBACK_INFO',
  SEND_EPISODE_PROGRESS = 'UPDATE_EPISODE_PROGRESS',
  GET_EPISODE_PROGRESS = 'GET_EPISODE_PROGRESS',
}

export default ActionType;
