enum PlayerEvents {
  PLAYBACK_STATUS_CHANGE = 'PLAYER/PLAYBACK_STATUS_CHANGE',
  PLAYBACK_END = 'PLAYER/PLAYBACK_END',
  PLAYBACK_START = 'PLAYER/PLAYBACK_START',
  VOLUME_CHANGE = 'PLAYER/VOLUME_CHANGE',
  PROGRESS_CHANGE = 'PLAYER/PROGRESS_CHANGE',
  ERROR = 'PLAYER/ERROR',
}

export default PlayerEvents;
