name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16.0
      - name: Setup Node.js/Yarn environment
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: ^15.14.0
      - uses: actions/checkout@v2
      - name: Compile the frontend
        run: |
          cd webui/frontend
          yarn
          yarn build
          cd ../..
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: latest
          # Use the previously installed Go.
          skip-go-installation: true

          # Optional: working directory, useful for monorepos
          # working-directory: somedir

          # Optional: golangci-lint command line arguments.
          args: --enable sqlclosecheck --enable misspell --enable gofmt --enable goimports --enable whitespace

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true
